In [ ]:
numbers=[1,2,3,4,5,6,7,8]
min(numbers)

1

In [ ]:
sum(numbers)

36

In [ ]:
import random
numbers=[1,2,3,4,5,6,7,8]
random.shuffle(numbers)
print(numbers)

[1, 7, 3, 8, 5, 6, 4, 2]


In [ ]:
a=[10,30]
b=3*a
print(b)

[10, 30, 10, 30, 10, 30]


In [ ]:
days=["mon","tue","wed","thu","fri","sat","sun"]
"wed" in days

True

In [ ]:
days=["mon","tue","wed","thu","fri","sat","sun"]
"wed" not in days

False

In [ ]:
days=["mon","tue","wed","thu","fri","sat","sun"]
del[days[1]]
days

['mon', 'wed', 'thu', 'fri', 'sat', 'sun']

In [ ]:
a=["a","b","c","d"]
print(a)
a.append("e")
print(a)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e']


In [ ]:
list=["a","b","c","d"]
print(list)
list.clear()
print(list)

['a', 'b', 'c', 'd']
[]


In [ ]:
a=["a","b","c","d","a"]
a.count ("a")

2

In [ ]:
list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [ ]:
a=[1,2,3,4,5]
b=[5,6,7,8,9]
print(a)
print(b)
a.extend(b)
print(a)

[1, 2, 3, 4, 5]
[5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [ ]:
a=(5,)
print(a)
print(type(a))

(5,)
<class 'tuple'>


In [ ]:
mix=["hello",245,55.4,33,6,]
mix

['hello', 245, 55.4, 33, 6]

In [ ]:
a={
    "name":"sujal",
    "age":20,
    "city":"surat",
    "phone":1234567890
}
print(a)


{'name': 'sujal', 'age': 20, 'city': 'surat', 'phone': 1234567890}


In [ ]:
len(a)

4

In [ ]:
z=a.items()
print(z)

dict_items([('name', 'sujal'), ('age', 20), ('city', 'surat'), ('phone', 1234567890)])


In [ ]:
set={1,2,3,4,5,6,7,8}
print(set)

{1, 2, 3, 4, 5, 6, 7, 8}


In [ ]:
set={1,2,3,4,5,6,7,8,1,1}
set

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
def add():
    a=10
    b=20
    sum=a+b
    return sum
add()
print(add())

30


In [ ]:
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z2.size

12

In [ ]:
z2.shape

(3, 4)

In [ ]:
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
a2=np.ones([3,4])
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a2=np.ones([3,4],dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
a2.ndim

2

In [ ]:
a3=np.ones([3,4,5])
a3

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
f2=np.full([2,3],9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
sub=np.add(a,b)
sub

array([5, 7, 9])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
sub=np.power(a,b)
sub

array([  1,  32, 729])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
sub=np.multiply(a,b)
sub

array([ 4, 10, 18])