In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np

In [ ]:
A1=np.array([1,2,3,4,5])
print(A1)

[1 2 3 4 5]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(5,)

In [ ]:
A1.shape

(5,)

In [ ]:
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
A1.size

5

In [ ]:
A3=np.array([[[1,2,3,4],[5,6,7,8],[[1,2,3,4]]])
print(A3)

In [ ]:
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
z1.shape

(3,)

In [ ]:
z1.ndim

1

In [ ]:
z2=np.zeros((2,3))
z2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z2=np.zeros((2,3),dtype=int)
z2

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [ ]:
a2=np.ones((2,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a3=np.ones([4,2,3])
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])